name: curriculum test

on:
  push:
      paths:
        - '**.docx'
        - 'WorkingPlans/**'
  pull_request:
    paths:
        - '**.docx'
        - 'WorkingPlans/**'

jobs:
  competence:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
