name: unit tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Curriculum test
      run: cd CurriculumParser.UnitTests && dotnet test /p:CollectCoverage=true 
    - name: Warnings test
      run: cd ~/Warnings.UnitTests && dotnet test /p:CollectCoverage=true 
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./Warnings.UnitTests/coverage.json,./CurriculumParser.UnitTests/coverage.json
        flags: unittests
        verbose: true
